### ISSUE TITLE
Release WORKSPACE snippet with wrong rule name

### ISSUE THREAD

**Issue by andre-alves** [thii/rules_swiftlint#1]
Hi!

The `http_archive` name doesn't match the rest of the snippet (and other parts of the documentation)

https://github.com/thii/rules_swiftlint/releases/tag/0.2.0

It's currently `rules_swiftlint` but it should be `com_github_thii_rules_swiftlint`.

**Comment by thii** [comment]
Thanks for reporting, I've updated the snippet.
